apiVersion: v1
kind: List
items:
- kind: Service
  apiVersion: v1
  metadata:
    name: partya
  spec:
    selector:
      app: partya
    ports:
    - protocol: TCP
      port: 30000
      targetPort: 30000
      name: p2p
    - protocol: TCP
      port: 10001
      targetPort: 10001
      name: rpc
    - protocol: TCP
      port: 2222
      targetPort: 2222
      name: ssh
    clusterIP: 10.96.0.100 
- kind: Deployment
  apiVersion: apps/v1
  metadata:
    name: partya
    labels:
      app: partya
  spec:
    selector: 
        matchLabels:
            app: partya
    replicas: 1
    strategy:
      type: Recreate
      rollingUpdate: null
    template:
      metadata:
        labels:
          app: partya
      spec:
        nodeSelector:
          kubernetes.io/hostname: <partya_host>
        containers:
        - name: cordapp
          image: masterops/corda-os-node:4.5
          resources:
            limits:
              memory: "2Gi"
            requests:
              memory: "1Gi"
          ports:
            - containerPort: 30000
              name: p2p
            - containerPort: 10001
              name: rpc
            - containerPort: 2222
              name: ssh
          volumeMounts:
          - name: node-config
            mountPath: "/opt/corda/node.conf"
            subPath: "node.conf"
            readOnly: true
          - name: node-config
            mountPath: "/opt/corda/network-parameters"
            subPath: "network-parameters"
            readOnly: true
          - name: node-certificates
            mountPath: "/opt/corda/certificates"
            readOnly: true
        volumes:
        - name: node-config
          secret:
            secretName: partya-config
        - name: node-certificates
          secret:
            secretName: partya-keystore

            
            
            
